name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout Actions
        uses: actions/checkout@main
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: Simple JavaScript Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: John Smith
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"