name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Simple JavaScript Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: John Smith
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"