name: Container
on: push

# jobs:
#   node-docker:
#     runs-on: ubuntu-latest
#     container: 
#       image: node:13.5.0-alpine3.10
#     steps:
#       - name: Log node version
#         run: |
#           node -v
#           cat /etc/os-release

# jobs:
#   node-docker:
#     runs-on: ubuntu-latest
#     services:
#       app:
#         image: alialaa17/node-api
#         ports:
#           - 3001:3000
#       mongo:
#         image: mongo
#         ports:
#           - "27017:27017"
#     steps:
#       - name: Post a user
#         run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d ' {\"username\": \"hello\",\"address\": \"dwded\"}'"
#       - name: Get Users
#         run: curl http://localhost:3001/api/users



jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Log node version
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: "/usr/local/bin/node"
          args: "-v"
      - name: Log OS version
        uses: docker://node:16.1.0-alpine3.11
        with: 
          entrypoint: "/bin/cat"
          args: "/etc/os-release"